services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: pnpm run start:dev
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
volumes:
  .:
networks:
  app-network:
